amcl:
  ros__parameters:
    use_sim_time: False
    alpha1: 0.2       # 旋转噪声系数
    alpha2: 0.2       # 旋转-平移耦合噪声系数
    alpha3: 0.2       # 平移噪声系数
    alpha4: 0.2       # 平移-旋转耦合噪声系数
    alpha5: 0.1       # 平移噪声系数（仅差分驱动）
    base_frame_id: "base_footprint"  # 机器人底座坐标系
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    do_beamskip: false
    global_frame_id: "map"  # 全局坐标系（地图）
    lambda_short: 0.1
    laser_likelihood_max_dist: 2.0  # 激光最大有效距离
    laser_max_range: 3.5            # 激光硬件最大距离
    laser_min_range: 0.1            # 激光硬件最小距离
    max_beams: 60                   # 每次更新使用的激光束数量
    max_particles: 2000             # 粒子滤波最大粒子数
    min_particles: 500              # 粒子滤波最小粒子数
    odom_frame_id: "odom"           # 里程计坐标系
    pf_err: 0.05
    pf_z: 0.99
    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0
    resample_interval: 1
    robot_model_type: "differential"  # 机器人模型（差分驱动）
    save_pose_rate: 0.5
    sigma_hit: 0.2
    tf_broadcast: true
    transform_tolerance: 0.1
    update_min_a: 0.2               # 最小旋转更新阈值（rad）
    update_min_d: 0.2               # 最小平移更新阈值（m）
    z_hit: 0.95
    z_max: 0.05
    z_rand: 0.0
    z_short: 0.0/home/robot/HBRobot/src/robot_launch/config/nav2_params (copy).yaml
