obstacle_range: 3
raytrace_range: 3.0
#robot_radius: 0.3
footprint: [[0.4, 0], [0.35, -0.35],[-0.35, -0.35],[-0.35, 0.35],[0.35, 0.35]]
inflation_radius: 0.5
max_obstacle_height: 2
min_obstacle_height: -2
observation_sources: scan velodyne_points
scan: {data_type: LaserScan, sensor_frame: /laser, topic: /scan, expected_update_rate: 0.1,
observation_persistence: 0.0, marking: true, clearing: true, max_obstacle_height: 2.0, min_obstacle_height: -1.0,inf_is_valid: true,observation_keep_time: 0.0}
velodyne_points: {sensor_frame: velodyne, data_type: PointCloud, topic: velodyne_points, marking: true, clearing: true, max_obstacle_height: 2.0, min_obstacle_height: -1.0}

