default_params:
  default_cylinder_radius: 0.05
  default_cylinder_color:
    - 1
    - 0
    - 0
    - 0.8
  default_cuboid_offset:
    - 0
    - 0
    - 0
  default_cuboid_size:
    - 0.08
    - 0.08
    - 0.08
  default_cuboid_color:
    - 0
    - 1
    - 0
    - 0.8
  default_cuboid_rotate:
    - 0
    - 0
    - 0
cylinder_radii:
  - 0.5
  - 0.3
  - 0.3
  - 0.2
  - 0.2
cylinder_colors:
  -
    - 1
    - 0
    - 0
    - 1
  -
    - 1
    - 0
    - 0
    - 1
  -
    - 1
    - 0
    - 0
    - 1
  -
    - 1
    - 0
    - 0
    - 1
  -
    - 1
    - 0
    - 0
    - 1
cuboid_offsets:
  -
    - 0
    - 0
    - 0.6
  -
    - 0
    - 0
    - 0
  -
    - 0
    - 0
    - 0
  -
    - 0
    - 0
    - 0
  -
    - 0
    - 0
    - 0
  -
    - 0
    - 0
    - 0
cuboid_sizes:
  -
    - 3.2
    - 1.5
    - 2
  -
    - 0.08
    - 0.08
    - 0.15
  -
    - 0.08
    - 0.08
    - 0.15
  -
    - 0.08
    - 0.08
    - 0.15
  -
    - 0.08
    - 0.08
    - 0.15
  -
    - 3.2
    - 0.2
    - 0.2
cuboid_colors:
  -
    - 0
    - 1
    - 0
    - 0.8
  -
    - 0
    - 1
    - 0
    - 0.8
  -
    - 0
    - 1
    - 0
    - 0.8
  -
    - 0
    - 1
    - 0
    - 0.8
  -
    - 0
    - 1
    - 0
    - 0.8
  -
    - 0
    - 1
    - 0
    - 0.8
cuboid_rotates:
  -
    - 0
    - 0
    - 0
  -
    - 0
    - 0
    - 0
  -
    - 0
    - 0
    - 0
  -
    - 0
    - 0
    - 0
  -
    - 0
    - 0
    - 0
  -
    - 0
    - 0
    - 0