# CAN 总线配置
bus:
  device: "vcan0"  # 对应步骤 1 配置的 CAN 接口名
  baudrate: 500000       # 波特率（需与从站设备一致）
  sync_interval: 10000    # 同步周期（单位：us，10000=10ms，即 100Hz）
  heartbeat: 1000         # 心跳周期（单位：ms，0 表示禁用）
  loopback: true        # 是否启用环回模式（仅用于测试）
sync:
  interval_ms: 1000      # 同步报文发送间隔（单位：ms，0 表示禁用）
  overflow: 20         # 是否启用同步溢出检测

# 从站节点列表（多个从站按 ID 排序）
nodes:
  - name: "motor1"      # 从站名称（自定义）
    id: 1               # 从站节点 ID（需与硬件拨码开关一致）
    eds_file: "/home/robot/XProbot/src/package/ros_canopen/canopen_chain_node/config/node.eds"  # EDS 文件路径
    dcf_overlay: {}     # 可选：覆盖 EDS 中的参数（如修改对象字典值）

  - name: "motor2"
    id: 2
    eds_file: "/home/robot/XProbot/src/package/ros_canopen/canopen_chain_node/config/node.eds"
    dcf_overlay: {}
