common:
  dataset: "nclt"
  lid_topic: "/velodyne_points"
  imu_topic: "/imu"
  time_sync_en: true         # ONLY turn on when external time synchronization is really not possible

preprocess:
  lidar_type: 2                # 1 for Livox serials LiDAR, 2 for Velodyne LiDAR, 3 for ouster LiDAR,
  scan_line: 16
  blind: 2
  time_scale: 1e-9             # 兼容不同数据集的时间单位，仅对Velodyne LiDAR(lidar_type=2)生效

mapping:
  acc_cov: 0.1
  gyr_cov: 0.1
  b_acc_cov: 0.0001
  b_gyr_cov: 0.0001
  fov_degree: 360
  det_range: 1000.0
  extrinsic_est_en: true      # true: enable the online estimation of IMU-LiDAR extrinsic
  extrinsic_T: [ 0, 0, 0.02 ]
  extrinsic_R: [ 1, 0, 0,
                 0, 1, 0,
                 0, 0, 1 ]

publish:
  path_publish_en: false
  scan_publish_en: false       # false: close all the point cloud output
  scan_effect_pub_en: false    # true: publish the pointscloud of effect point
  dense_publish_en: false       # false: low down the points number in a global-frame point clouds scan.
  scan_bodyframe_pub_en: true  # true: output the point cloud scans in IMU-body-frame
  tf_imu_frame: "lidar_footprint"
  tf_world_frame: "odom"
  odometry_topic: "/faster_lio/odometry"
  # odometry_topic: "/lvi_sam/odom"
  path_topic: "/faster_lio/path"

path_save_en: false                 # 保存轨迹，用于精度计算和比较

pcd_save:
  pcd_save_en: false
  interval: -1                 # how many LiDAR frames saved in each pcd file;
  # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.

feature_extract_enable: false
point_filter_num: 6
max_iteration: 3
filter_size_surf: 0.1
filter_size_map: 0.1
cube_side_length: 1000

ivox_grid_resolution: 0.5        # default=0.2
ivox_nearby_type: 18             # 6, 18, 26
esti_plane_threshold: 0.1        # default=0.1
